version: "2"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: {{cookiecutter.project_slug}}
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ".:/code"
    command: python manage.py runserver 0:8000

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "./data/db:/var/lib/postgresql/data"
